name: Duplicate code

on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@action_check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "./"
          ignore_threshold: 0
